project_id = "kqwqqygnxpljcfpxuywh"

[functions.approve-signup]
verify_jwt = true

[functions.request-password-reset]
verify_jwt = false

[functions.invite-member]
verify_jwt = true

[functions.create-member-login]
verify_jwt = true

[functions.generate-jitsi-jwt]
verify_jwt = true

[functions.generate-module-certificate]
verify_jwt = true
